DataSecurityEvents
| where Timestamp > ago(7d)
| where isnotempty(SensitivityLabelId)
| where ActionType in ("FileUploadedToCloud","FileSharedExternally","FileSentInEmail")
| project Timestamp, AccountUpn, ActionType, ObjectId, SourceRelativeUrl, TargetFilePath,
          ApplicationNames, Workload, SensitivityLabelId,
          TargetUrlDomain, EmailSubject, NetworkMessageId
| order by Timestamp desc